# Generated by Django 3.0.5 on 2020-04-26 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200425_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryjob',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
