# Generated by Django 3.0.5 on 2020-04-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200426_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='query_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='any_ip_addr', to='API.QueryJob'),
        ),
    ]
