# Generated by Django 3.0.5 on 2020-04-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200426_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='query_type',
        ),
    ]
