# Generated by Django 3.0.5 on 2020-04-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_ip_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='query_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='any_ip_addr', to='API.QueryJob'),
            preserve_default=False,
        ),
    ]
