# Generated by Django 3.0.5 on 2020-04-26 12:53

import API.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_ip_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryjob',
            name='hostname',
            field=models.CharField(blank=True, max_length=1040),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='ip_address',
            field=models.CharField(blank=True, max_length=1040, validators=[API.validators.validate_ips]),
        ),
    ]
