# Generated by Django 3.0.5 on 2020-04-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200426_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryjob',
            old_name='ip_address',
            new_name='any_ip_addr',
        ),
        migrations.AlterField(
            model_name='ip',
            name='query_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.QueryJob'),
        ),
    ]
