# Generated by Django 3.0.5 on 2020-04-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200426_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryjob',
            old_name='hostname',
            new_name='ptr',
        ),
    ]
