# Generated by Django 3.0.5 on 2020-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200426_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryjob',
            old_name='any_ip_addr',
            new_name='ip_addr',
        ),
        migrations.AddField(
            model_name='query',
            name='any_ip_addr',
            field=models.CharField(default='10.0.0.1', max_length=1040),
            preserve_default=False,
        ),
    ]
