# Generated by Django 3.0.6 on 2020-06-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200426_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryjob',
            name='augury_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
