# Generated by Django 3.0.6 on 2020-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_results_augury_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='augury_job_id',
            new_name='aug_job_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='augury_response',
            new_name='aug_response',
        ),
    ]
