# Generated by Django 3.0.6 on 2020-06-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20200603_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='aug_response',
            new_name='aug_results',
        ),
    ]
